# Uncomment the next line to define a global platform for your project
# platform :ios, '14.0'

flutter_application_path = '../zeek_flutter_module'

load File.join(flutter_application_path,'.ios','Flutter','podhelper.rb')

target 'flutterTestApp' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for flutterTestApp
  install_all_flutter_pods(flutter_application_path)

end
